api_platform:
  title: Hello API Platform
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    normalization_context:
      enable_max_depth: true
framework:
  serializer:
    enable_annotations: true
    default_context:
      enable_max_depth: true
