security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  access_control:
    # Routes publiques
    - { path: ^/api/listings, roles: PUBLIC_ACCESS }
    - { path: ^/api/services, roles: PUBLIC_ACCESS }
    - { path: ^/api/equipment, roles: PUBLIC_ACCESS }
    - { path: ^/api/pictures, roles: PUBLIC_ACCESS }
    - { path: ^/api/users$, roles: PUBLIC_ACCESS, methods: [POST] }
    - { path: ^/api/addresses$, roles: PUBLIC_ACCESS, methods: [POST] }
    - { path: ^/api/login, roles: PUBLIC_ACCESS }

    # Routes nécessitant authentification
    - { path: ^/api/me, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
