parameters:

services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  Gedmo\Sortable\SortableListener:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  App\State\UserPasswordHasher:
    arguments:
      $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"
    tags:
      - {
          name: "api_platform.state_processor",
          priority: 10,
          operation: 'App\Entity\User:post',
        }
